# CPSC 330 - Applied Machine Learning 

## Homework 8: Time series

### Associated lectures: [Lectures 19 and 20](https://github.com/UBC-CS/cpsc330-2024s/tree/main/lectures)

**See PrairieLearn for _due date_ and _submission_**

## Imports

In [1]:
from hashlib import sha1

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

from sklearn.impute import SimpleImputer
from sklearn.compose import ColumnTransformer, make_column_transformer
from sklearn.pipeline import Pipeline, make_pipeline
from sklearn.preprocessing import StandardScaler, OrdinalEncoder, OneHotEncoder

from sklearn.linear_model import Ridge
from sklearn.ensemble import RandomForestRegressor

from sklearn.metrics import r2_score

## Submission instructions
<hr>

_points: 2_

You will receive marks for correctly submitting this assignment. To submit this assignment, follow the instructions below:

- **You may work on this assignment in a group (group size $\leq$ 4) and submit your assignment as a group.** 
- Below are some instructions on working as a group.  
    - The maximum group size is 4. 
    - You can choose your own group members. 
    - Use group work as an opportunity to collaborate and learn new things from each other. 
    - Be respectful to each other and make sure you understand all the concepts in the assignment well. 
    - It's your responsibility to make sure that the assignment is submitted by one of the group members before the deadline. [Here](https://help.gradescope.com/article/m5qz2xsnjy-student-add-group-members) are some instructions on adding group members in Gradescope.  
- Be sure to follow the [homework submission instructions](https://github.com/UBC-CS/cpsc330-2024s/blob/main/docs/homework_instructions.md).
- Upload the .ipynb file to PrairieLearn.

<br><br>

## Exercise 1: time series prediction

In this exercise we'll be looking at a [dataset of avocado prices](https://www.kaggle.com/neuromusic/avocado-prices). You should start by downloading the dataset. We will be forcasting average avocado price for the next week.

In [2]:
df = pd.read_csv("data/avocado.csv", parse_dates=["Date"], index_col=0)
df.head()

,Date,AveragePrice,Total Volume,4046,4225,4770,Total Bags,Small Bags,Large Bags,XLarge Bags,type,year,region
0,2015-12-27,1.33,64236.62,1036.74,54454.85,48.16,8696.87,8603.62,93.25,0.0,conventional,2015,Albany
1,2015-12-20,1.35,54876.98,674.28,44638.81,58.33,9505.56,9408.07,97.49,0.0,conventional,2015,Albany
2,2015-12-13,0.93,118220.22,794.70,109149.67,130.50,8145.35,8042.21,103.14,0.0,conventional,2015,Albany
3,2015-12-06,1.08,78992.15,1132.00,71976.41,72.58,5811.16,5677.40,133.76,0.0,conventional,2015,Albany
4,2015-11-29,1.28,51039.60,941.48,43838.39,75.78,6183.95,5986.26,197.69,0.0,conventional,2015,Albany

In [3]:
df.shape

(18249, 13)

In [4]:
df["Date"].min()

Timestamp('2015-01-04 00:00:00')

In [5]:
df["Date"].max()

Timestamp('2018-03-25 00:00:00')

It looks like the data ranges from the start of 2015 to March 2018 (~2 years ago), for a total of 3.25 years or so. Let's split the data so that we have a 6 months of test data.

In [6]:
split_date = '20170925'
df_train = df[df["Date"] <= split_date]
df_test  = df[df["Date"] >  split_date]

In [7]:
assert len(df_train) + len(df_test) == len(df)

<br><br>

<!-- BEGIN QUESTION -->

### 1.1 How many time series? 

_Points:_ 4

In the [Rain in Australia](https://www.kaggle.com/datasets/jsphyg/weather-dataset-rattle-package) dataset from lecture, we had different measurements for each Location. How about this avocado sales dataset? For which categorical feature(s), if any, do we have separate measurements? Justify your answer by referencing the dataset.

<div class="alert alert-warning">

Solution_1.1
    
</div>

In [8]:
df_train.sort_values(by="Date").head(10)

,Date,AveragePrice,Total Volume,4046,4225,4770,Total Bags,Small Bags,Large Bags,XLarge Bags,type,year,region
50,2015-01-04,1.64,6182.81,1561.30,2958.17,0.00,1663.34,1663.34,0.00,0.00,organic,2015,WestTexNewMexico
51,2015-01-04,1.00,435021.49,364302.39,23821.16,82.15,46815.79,16707.15,30108.64,0.00,conventional,2015,Atlanta
51,2015-01-04,1.93,17328.24,2357.18,12692.21,9.47,2269.38,2269.38,0.00,0.00,organic,2015,NewYork
51,2015-01-04,1.02,160130.15,4007.41,118435.79,1201.50,36485.45,20325.41,16160.04,0.00,conventional,2015,Indianapolis
51,2015-01-04,1.69,34190.37,3874.31,14945.34,32.45,15338.27,13793.22,1545.05,0.00,organic,2015,Plains
51,2015-01-04,1.18,22630.58,13175.57,9028.34,0.00,426.67,426.67,0.00,0.00,organic,2015,SanFrancisco
51,2015-01-04,0.97,599965.86,126485.75,377138.79,19781.57,76559.75,61308.73,15251.02,0.00,conventional,2015,Portland
51,2015-01-04,0.74,1086363.97,612795.80,374420.68,9817.28,89330.21,54563.33,34760.08,6.80,conventional,2015,DallasFtWorth
51,2015-01-04,1.24,142349.77,107490.73,25711.96,2.93,9144.15,9144.15,0.00,0.00,organic,2015,California
51,2015-01-04,0.89,5794410.58,2275446.87,2582300.65,97024.09,839638.97,688813.01,150819.57,6.39,conventional,2015,West

In [9]:
df_train.sort_values(by=["region",'Date']).head(10)

,Date,AveragePrice,Total Volume,4046,4225,4770,Total Bags,Small Bags,Large Bags,XLarge Bags,type,year,region
51,2015-01-04,1.22,40873.28,2819.50,28287.42,49.90,9716.46,9186.93,529.53,0.0,conventional,2015,Albany
51,2015-01-04,1.79,1373.95,57.42,153.88,0.00,1162.65,1162.65,0.00,0.0,organic,2015,Albany
50,2015-01-11,1.24,41195.08,1002.85,31640.34,127.12,8424.77,8036.04,388.73,0.0,conventional,2015,Albany
50,2015-01-11,1.77,1182.56,39.00,305.12,0.00,838.44,838.44,0.00,0.0,organic,2015,Albany
49,2015-01-18,1.17,44511.28,914.14,31540.32,135.77,11921.05,11651.09,269.96,0.0,conventional,2015,Albany
49,2015-01-18,1.93,1118.47,8.02,178.78,0.00,931.67,931.67,0.00,0.0,organic,2015,Albany
48,2015-01-25,1.06,45147.50,941.38,33196.16,164.14,10845.82,10103.35,742.47,0.0,conventional,2015,Albany
48,2015-01-25,1.89,1115.89,14.87,148.72,0.00,952.30,952.30,0.00,0.0,organic,2015,Albany
47,2015-02-01,0.99,70873.60,1353.90,60017.20,179.32,9323.18,9170.82,152.36,0.0,conventional,2015,Albany
47,2015-02-01,1.83,1228.51,33.12,99.36,0.00,1096.03,1096.03,0.00,0.0,organic,2015,Albany

In [10]:
print(len(df_train['region'].value_counts().index))

54

In [11]:
print(list(df_train['region'].value_counts().index))

['Albany', 'Sacramento', 'Northeast', 'NorthernNewEngland', 'Orlando', 'Philadelphia', 'PhoenixTucson', 'Pittsburgh', 'Plains', 'Portland', 'RaleighGreensboro', 'RichmondNorfolk', 'Roanoke', 'SanDiego', 'Atlanta', 'SanFrancisco', 'Seattle', 'SouthCarolina', 'SouthCentral', 'Southeast', 'Spokane', 'StLouis', 'Syracuse', 'Tampa', 'TotalUS', 'West', 'NewYork', 'NewOrleansMobile', 'Nashville', 'Midsouth', 'BaltimoreWashington', 'Boise', 'Boston', 'BuffaloRochester', 'California', 'Charlotte', 'Chicago', 'CincinnatiDayton', 'Columbus', 'DallasFtWorth', 'Denver', 'Detroit', 'GrandRapids', 'GreatLakes', 'HarrisburgScranton', 'HartfordSpringfield', 'Houston', 'Indianapolis', 'Jacksonville', 'LasVegas', 'LosAngeles', 'Louisville', 'MiamiFtLauderdale', 'WestTexNewMexico']

We have separate measurements for `region` and `type`.

<!-- END QUESTION -->

<br><br>

<!-- BEGIN QUESTION -->

### 1.2 Equally spaced measurements? 

_Points:_ 4

In the Rain in Australia dataset, the measurements were generally equally spaced but with some exceptions. How about with this dataset? Justify your answer by referencing the dataset.

<div class="alert alert-warning">

Solution_1.2
    
</div>

In [12]:
for name, group in df_train.groupby(["region",'type']):
    print("%-30s %s" % (name, group["Date"].sort_values().diff().value_counts()))
    print('\n\n\n')

('Albany', 'conventional')     Date
7 days    142
Name: count, dtype: int64




('Albany', 'organic')          Date
7 days    142
Name: count, dtype: int64




('Atlanta', 'conventional')    Date
7 days    142
Name: count, dtype: int64




('Atlanta', 'organic')         Date
7 days    142
Name: count, dtype: int64




('BaltimoreWashington', 'conventional') Date
7 days    142
Name: count, dtype: int64




('BaltimoreWashington', 'organic') Date
7 days    142
Name: count, dtype: int64




('Boise', 'conventional')      Date
7 days    142
Name: count, dtype: int64




('Boise', 'organic')           Date
7 days    142
Name: count, dtype: int64




('Boston', 'conventional')     Date
7 days    142
Name: count, dtype: int64




('Boston', 'organic')          Date
7 days    142
Name: count, dtype: int64




('BuffaloRochester', 'conventional') Date
7 days    142
Name: count, dtype: int64




('BuffaloRochester', 'organic') Date
7 days    142
Name: count, dtype: int64




('California', 'conventional') Date
7 days    142
Name: count, dtype: int64




('California', 'organic')      Date
7 days    142
Name: count, dtype: int64




('Charlotte', 'conventional')  Date
7 days    142
Name: count, dtype: int64




('Charlotte', 'organic')       Date
7 days    142
Name: count, dtype: int64




('Chicago', 'conventional')    Date
7 days    142
Name: count, dtype: int64




('Chicago', 'organic')         Date
7 days    142
Name: count, dtype: int64




('CincinnatiDayton', 'conventional') Date
7 days    142
Name: count, dtype: int64




('CincinnatiDayton', 'organic') Date
7 days    142
Name: count, dtype: int64




('Columbus', 'conventional')   Date
7 days    142
Name: count, dtype: int64




('Columbus', 'organic')        Date
7 days    142
Name: count, dtype: int64




('DallasFtWorth', 'conventional') Date
7 days    142
Name: count, dtype: int64




('DallasFtWorth', 'organic')   Date
7 days    142
Name: count, dtype: int64




('Denver', 'conventional')     Date
7 days    142
Name: count, dtype: int64




('Denver', 'organic')          Date
7 days    142
Name: count, dtype: int64




('Detroit', 'conventional')    Date
7 days    142
Name: count, dtype: int64




('Detroit', 'organic')         Date
7 days    142
Name: count, dtype: int64




('GrandRapids', 'conventional') Date
7 days    142
Name: count, dtype: int64




('GrandRapids', 'organic')     Date
7 days    142
Name: count, dtype: int64




('GreatLakes', 'conventional') Date
7 days    142
Name: count, dtype: int64




('GreatLakes', 'organic')      Date
7 days    142
Name: count, dtype: int64




('HarrisburgScranton', 'conventional') Date
7 days    142
Name: count, dtype: int64




('HarrisburgScranton', 'organic') Date
7 days    142
Name: count, dtype: int64




('HartfordSpringfield', 'conventional') Date
7 days    142
Name: count, dtype: int64




('HartfordSpringfield', 'organic') Date
7 days    142
Name: count, dtype: int64




('Houston', 'conventional')    Date
7 days    142
Name: count, dtype: int64




('Houston', 'organic')         Date
7 days    142
Name: count, dtype: int64




('Indianapolis', 'conventional') Date
7 days    142
Name: count, dtype: int64




('Indianapolis', 'organic')    Date
7 days    142
Name: count, dtype: int64




('Jacksonville', 'conventional') Date
7 days    142
Name: count, dtype: int64




('Jacksonville', 'organic')    Date
7 days    142
Name: count, dtype: int64




('LasVegas', 'conventional')   Date
7 days    142
Name: count, dtype: int64




('LasVegas', 'organic')        Date
7 days    142
Name: count, dtype: int64




('LosAngeles', 'conventional') Date
7 days    142
Name: count, dtype: int64




('LosAngeles', 'organic')      Date
7 days    142
Name: count, dtype: int64




('Louisville', 'conventional') Date
7 days    142
Name: count, dtype: int64




('Louisville', 'organic')      Date
7 days    142
Name: count, dtype: int64




('MiamiFtLauderdale', 'conventional') Date
7 days    142
Name: count, dtype: int64




('MiamiFtLauderdale', 'organic') Date
7 days    142
Name: count, dtype: int64




('Midsouth', 'conventional')   Date
7 days    142
Name: count, dtype: int64




('Midsouth', 'organic')        Date
7 days    142
Name: count, dtype: int64




('Nashville', 'conventional')  Date
7 days    142
Name: count, dtype: int64




('Nashville', 'organic')       Date
7 days    142
Name: count, dtype: int64




('NewOrleansMobile', 'conventional') Date
7 days    142
Name: count, dtype: int64




('NewOrleansMobile', 'organic') Date
7 days    142
Name: count, dtype: int64




('NewYork', 'conventional')    Date
7 days    142
Name: count, dtype: int64




('NewYork', 'organic')         Date
7 days    142
Name: count, dtype: int64




('Northeast', 'conventional')  Date
7 days    142
Name: count, dtype: int64




('Northeast', 'organic')       Date
7 days    142
Name: count, dtype: int64




('NorthernNewEngland', 'conventional') Date
7 days    142
Name: count, dtype: int64




('NorthernNewEngland', 'organic') Date
7 days    142
Name: count, dtype: int64




('Orlando', 'conventional')    Date
7 days    142
Name: count, dtype: int64




('Orlando', 'organic')         Date
7 days    142
Name: count, dtype: int64




('Philadelphia', 'conventional') Date
7 days    142
Name: count, dtype: int64




('Philadelphia', 'organic')    Date
7 days    142
Name: count, dtype: int64




('PhoenixTucson', 'conventional') Date
7 days    142
Name: count, dtype: int64




('PhoenixTucson', 'organic')   Date
7 days    142
Name: count, dtype: int64




('Pittsburgh', 'conventional') Date
7 days    142
Name: count, dtype: int64




('Pittsburgh', 'organic')      Date
7 days    142
Name: count, dtype: int64




('Plains', 'conventional')     Date
7 days    142
Name: count, dtype: int64




('Plains', 'organic')          Date
7 days    142
Name: count, dtype: int64




('Portland', 'conventional')   Date
7 days    142
Name: count, dtype: int64




('Portland', 'organic')        Date
7 days    142
Name: count, dtype: int64




('RaleighGreensboro', 'conventional') Date
7 days    142
Name: count, dtype: int64




('RaleighGreensboro', 'organic') Date
7 days    142
Name: count, dtype: int64




('RichmondNorfolk', 'conventional') Date
7 days    142
Name: count, dtype: int64




('RichmondNorfolk', 'organic') Date
7 days    142
Name: count, dtype: int64




('Roanoke', 'conventional')    Date
7 days    142
Name: count, dtype: int64




('Roanoke', 'organic')         Date
7 days    142
Name: count, dtype: int64




('Sacramento', 'conventional') Date
7 days    142
Name: count, dtype: int64




('Sacramento', 'organic')      Date
7 days    142
Name: count, dtype: int64




('SanDiego', 'conventional')   Date
7 days    142
Name: count, dtype: int64




('SanDiego', 'organic')        Date
7 days    142
Name: count, dtype: int64




('SanFrancisco', 'conventional') Date
7 days    142
Name: count, dtype: int64




('SanFrancisco', 'organic')    Date
7 days    142
Name: count, dtype: int64




('Seattle', 'conventional')    Date
7 days    142
Name: count, dtype: int64




('Seattle', 'organic')         Date
7 days    142
Name: count, dtype: int64




('SouthCarolina', 'conventional') Date
7 days    142
Name: count, dtype: int64




('SouthCarolina', 'organic')   Date
7 days    142
Name: count, dtype: int64




('SouthCentral', 'conventional') Date
7 days    142
Name: count, dtype: int64




('SouthCentral', 'organic')    Date
7 days    142
Name: count, dtype: int64




('Southeast', 'conventional')  Date
7 days    142
Name: count, dtype: int64




('Southeast', 'organic')       Date
7 days    142
Name: count, dtype: int64




('Spokane', 'conventional')    Date
7 days    142
Name: count, dtype: int64




('Spokane', 'organic')         Date
7 days    142
Name: count, dtype: int64




('StLouis', 'conventional')    Date
7 days    142
Name: count, dtype: int64




('StLouis', 'organic')         Date
7 days    142
Name: count, dtype: int64




('Syracuse', 'conventional')   Date
7 days    142
Name: count, dtype: int64




('Syracuse', 'organic')        Date
7 days    142
Name: count, dtype: int64




('Tampa', 'conventional')      Date
7 days    142
Name: count, dtype: int64




('Tampa', 'organic')           Date
7 days    142
Name: count, dtype: int64




('TotalUS', 'conventional')    Date
7 days    142
Name: count, dtype: int64




('TotalUS', 'organic')         Date
7 days    142
Name: count, dtype: int64




('West', 'conventional')       Date
7 days    142
Name: count, dtype: int64




('West', 'organic')            Date
7 days    142
Name: count, dtype: int64




('WestTexNewMexico', 'conventional') Date
7 days    142
Name: count, dtype: int64




('WestTexNewMexico', 'organic') Date
7 days     137
14 days      1
21 days      1
Name: count, dtype: int64

The typical spacing seems to be 7 day for each location with only two exceptions for `WestTexNewMexico` and `organic` - 14 days and 21 days. So I'd say in general the measurement is mostly equally spaced.

<!-- END QUESTION -->

<br><br>

<!-- BEGIN QUESTION -->

### 1.3 Interpreting regions 

_Points:_ 4

In the Rain in Australia dataset, each location was a different place in Australia. For this dataset, look at the names of the regions. Do you think the regions are also all distinct, or are there overlapping regions? Justify your answer by referencing the data.

<div class="alert alert-warning">

Solution_1.3
    
</div>

I think there are many overlaps. For example, there are many US cities and states, but it also has "TotalUS" as an entire category in `region`. It also contains areas like 'Northeast' or 'Midsouth' or 'West', but they contain cities or states like 'Boston' or 'Nashville' or 'California', respectively. Also, states such as 'California' already contain many existing categories of cities, such as 'Sacramento', 'San Diego', 'Los Angeles', and so on.

In [13]:
print(list(df['region'].unique()))

['Albany', 'Atlanta', 'BaltimoreWashington', 'Boise', 'Boston', 'BuffaloRochester', 'California', 'Charlotte', 'Chicago', 'CincinnatiDayton', 'Columbus', 'DallasFtWorth', 'Denver', 'Detroit', 'GrandRapids', 'GreatLakes', 'HarrisburgScranton', 'HartfordSpringfield', 'Houston', 'Indianapolis', 'Jacksonville', 'LasVegas', 'LosAngeles', 'Louisville', 'MiamiFtLauderdale', 'Midsouth', 'Nashville', 'NewOrleansMobile', 'NewYork', 'Northeast', 'NorthernNewEngland', 'Orlando', 'Philadelphia', 'PhoenixTucson', 'Pittsburgh', 'Plains', 'Portland', 'RaleighGreensboro', 'RichmondNorfolk', 'Roanoke', 'Sacramento', 'SanDiego', 'SanFrancisco', 'Seattle', 'SouthCarolina', 'SouthCentral', 'Southeast', 'Spokane', 'StLouis', 'Syracuse', 'Tampa', 'TotalUS', 'West', 'WestTexNewMexico']

<!-- END QUESTION -->

<br><br>

We will use the entire dataset despite any location-based weirdness uncovered in the previous part.

We will be trying to forecast the avocado price. The function below is adapted from [Lecture 19](https://github.com/UBC-CS/cpsc330-2023W2/blob/main/lectures/mathias/19_time-series.ipynb), with some improvements.

In [14]:
def create_lag_feature(df, orig_feature, lag, groupby, new_feature_name=None, clip=False):
    """
    Creates a new feature that's a lagged version of an existing one.
    
    NOTE: assumes df is already sorted by the time columns and has unique indices.
    
    Parameters
    ----------
    df : pandas.core.frame.DataFrame
        The dataset.
    orig_feature : str
        The column name of the feature we're copying
    lag : int
        The lag; negative lag means values from the past, positive lag means values from the future
    groupby : list
        Column(s) to group by in case df contains multiple time series
    new_feature_name : str
        Override the default name of the newly created column
    clip : bool
        If True, remove rows with a NaN values for the new feature
    
    Returns
    -------
    pandas.core.frame.DataFrame
        A new dataframe with the additional column added.
        
    """
        
    if new_feature_name is None:
        if lag < 0:
            new_feature_name = "%s_lag%d" % (orig_feature, -lag)
        else:
            new_feature_name = "%s_ahead%d" % (orig_feature, lag)
    
    new_df = df.assign(**{new_feature_name : np.nan})
    for name, group in new_df.groupby(groupby):        
        if lag < 0: # take values from the past
            new_df.loc[group.index[-lag:],new_feature_name] = group.iloc[:lag][orig_feature].values
        else:       # take values from the future
            new_df.loc[group.index[:-lag], new_feature_name] = group.iloc[lag:][orig_feature].values
            
    if clip:
        new_df = new_df.dropna(subset=[new_feature_name])
        
    return new_df

We first sort our dataframe properly:

In [15]:
df_sort = df.sort_values(by=["region", "type", "Date"]).reset_index(drop=True)
df_sort

,Date,AveragePrice,Total Volume,4046,4225,4770,Total Bags,Small Bags,Large Bags,XLarge Bags,type,year,region
0,2015-01-04,1.22,40873.28,2819.50,28287.42,49.90,9716.46,9186.93,529.53,0.0,conventional,2015,Albany
1,2015-01-11,1.24,41195.08,1002.85,31640.34,127.12,8424.77,8036.04,388.73,0.0,conventional,2015,Albany
2,2015-01-18,1.17,44511.28,914.14,31540.32,135.77,11921.05,11651.09,269.96,0.0,conventional,2015,Albany
3,2015-01-25,1.06,45147.50,941.38,33196.16,164.14,10845.82,10103.35,742.47,0.0,conventional,2015,Albany
4,2015-02-01,0.99,70873.60,1353.90,60017.20,179.32,9323.18,9170.82,152.36,0.0,conventional,2015,Albany
...,...,...,...,...,...,...,...,...,...,...,...,...,...
18244,2018-02-25,1.57,18421.24,1974.26,2482.65,0.00,13964.33,13698.27,266.06,0.0,organic,2018,WestTexNewMexico
18245,2018-03-04,1.54,17393.30,1832.24,1905.57,0.00,13655.49,13401.93,253.56,0.0,organic,2018,WestTexNewMexico
18246,2018-03-11,1.56,22128.42,2162.67,3194.25,8.93,16762.57,16510.32,252.25,0.0,organic,2018,WestTexNewMexico
18247,2018-03-18,1.56,15896.38,2055.35,1499.55,0.00,12341.48,12114.81,226.67,0.0,organic,2018,WestTexNewMexico
18248,2018-03-25,1.62,15303.40,2325.30,2171.66,0.00,10806.44,10569.80,236.64,0.0,organic,2018,WestTexNewMexico

We then call `create_lag_feature`. This creates a new column in the dataset `AveragePriceNextWeek`, which is the following week's `AveragePrice`. We have set `clip=True` which means it will remove rows where the target would be missing.

In [16]:
df_hastarget = create_lag_feature(df_sort, "AveragePrice", +1, ["region", "type"], "AveragePriceNextWeek", clip=True)
df_hastarget

,Date,AveragePrice,Total Volume,4046,4225,4770,Total Bags,Small Bags,Large Bags,XLarge Bags,type,year,region,AveragePriceNextWeek
0,2015-01-04,1.22,40873.28,2819.50,28287.42,49.90,9716.46,9186.93,529.53,0.0,conventional,2015,Albany,1.24
1,2015-01-11,1.24,41195.08,1002.85,31640.34,127.12,8424.77,8036.04,388.73,0.0,conventional,2015,Albany,1.17
2,2015-01-18,1.17,44511.28,914.14,31540.32,135.77,11921.05,11651.09,269.96,0.0,conventional,2015,Albany,1.06
3,2015-01-25,1.06,45147.50,941.38,33196.16,164.14,10845.82,10103.35,742.47,0.0,conventional,2015,Albany,0.99
4,2015-02-01,0.99,70873.60,1353.90,60017.20,179.32,9323.18,9170.82,152.36,0.0,conventional,2015,Albany,0.99
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
18243,2018-02-18,1.56,17597.12,1892.05,1928.36,0.00,13776.71,13553.53,223.18,0.0,organic,2018,WestTexNewMexico,1.57
18244,2018-02-25,1.57,18421.24,1974.26,2482.65,0.00,13964.33,13698.27,266.06,0.0,organic,2018,WestTexNewMexico,1.54
18245,2018-03-04,1.54,17393.30,1832.24,1905.57,0.00,13655.49,13401.93,253.56,0.0,organic,2018,WestTexNewMexico,1.56
18246,2018-03-11,1.56,22128.42,2162.67,3194.25,8.93,16762.57,16510.32,252.25,0.0,organic,2018,WestTexNewMexico,1.56
18247,2018-03-18,1.56,15896.38,2055.35,1499.55,0.00,12341.48,12114.81,226.67,0.0,organic,2018,WestTexNewMexico,1.62

Our goal is to predict `AveragePriceNextWeek`.

Let's split the data:

In [17]:
df_train = df_hastarget[df_hastarget["Date"] <= split_date]
df_test  = df_hastarget[df_hastarget["Date"] >  split_date]

<br><br>

### 1.4 `AveragePrice` baseline 

_Points:_ 4

Soon we will want to build some models to forecast the average avocado price a week in advance. Before we start with any ML though, let's try a baseline. Previously we used `DummyClassifier` or `DummyRegressor` as a baseline. This time, we'll do something else as a baseline: we'll assume the price stays the same from this week to next week. So, we'll set our prediction of "AveragePriceNextWeek" exactly equal to "AveragePrice", assuming no change. That is kind of like saying, "If it's raining today then I'm guessing it will be raining tomorrow". This simplistic approach will not get a great score but it's a good starting point for reference. If our model does worse that this, it must not be very good. 

Using this baseline approach, what $R^2$ do you get on the train and test data?

<div class="alert alert-warning">

Solution_1.4
    
</div>

_Type your answer here, replacing this text._

In [18]:
train_r2 = None

train_r2 = r2_score(df_train['AveragePriceNextWeek'],  df_train['AveragePrice'])
print(train_r2)

0.8285800937261841

In [19]:
test_r2 = None

test_r2 = r2_score(df_test['AveragePriceNextWeek'], df_test['AveragePrice'])
print(test_r2)

0.7631780188583048

<br><br>

<!-- BEGIN QUESTION -->

### 1.5 Forecasting average avocado price

_Points:_ 10

Now that the baseline is done, let's build some models to forecast the average avocado price a week later. Experiment with a few approachs for encoding the date. Justify the decisions you make. Which approach worked best? Report your test score and briefly discuss your results.

Benchmark: you should be able to achieve $R^2$ of at least 0.79 on the test set. We got to 0.80, but not beyond that. Let us know if you do better!

Note: because we only have 2 splits here, we need to be a bit wary of overfitting on the test set. Try not to test on it a ridiculous number of times. If you are interested in some proper ways of dealing with this, see for example sklearn's [TimeSeriesSplit](https://scikit-learn.org/stable/modules/generated/sklearn.model_selection.TimeSeriesSplit.html), which is like cross-validation for time series data.

<div class="alert alert-warning">

Solution_1.3
    
</div>

We first dropped the column `Total Bags`, as it is the sum of `Small Bags`, `Large Bags`, and `XLarge Bags` looking from the traning data. To preprocess the `Date` column, we used three different feature engineering methods: Encoding date as a number, One-Hot Encoding of the months, and One-Hot Encoding of the seasons.

By encoding date as numbers, the test score improved to 0.787 from the baseline (~0.76). By using OHE of months, the test score reached the highest among the three methods to 0.80. However, OHE of seasons didn't make any improvements from OHE of months, and the test score was still 0.79.

In [20]:
df_train.info()

<class 'pandas.core.frame.DataFrame'>
Index: 15441 entries, 0 to 18222
Data columns (total 14 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   Date                  15441 non-null  datetime64[ns]
 1   AveragePrice          15441 non-null  float64
 2   Total Volume          15441 non-null  float64
 3   4046                  15441 non-null  float64
 4   4225                  15441 non-null  float64
 5   4770                  15441 non-null  float64
 6   Total Bags            15441 non-null  float64
 7   Small Bags            15441 non-null  float64
 8   Large Bags            15441 non-null  float64
 9   XLarge Bags           15441 non-null  float64
 10  type                  15441 non-null  object
 11  year                  15441 non-null  int64
 12  region                15441 non-null  object
 13  AveragePriceNextWeek  15441 non-null  float64
dtypes: datetime64[ns](1), float64(10), int64(1), object(2)
memory usage: 1.8+ MB

In [21]:
df_train.head()

,Date,AveragePrice,Total Volume,4046,4225,4770,Total Bags,Small Bags,Large Bags,XLarge Bags,type,year,region,AveragePriceNextWeek
0,2015-01-04,1.22,40873.28,2819.50,28287.42,49.90,9716.46,9186.93,529.53,0.0,conventional,2015,Albany,1.24
1,2015-01-11,1.24,41195.08,1002.85,31640.34,127.12,8424.77,8036.04,388.73,0.0,conventional,2015,Albany,1.17
2,2015-01-18,1.17,44511.28,914.14,31540.32,135.77,11921.05,11651.09,269.96,0.0,conventional,2015,Albany,1.06
3,2015-01-25,1.06,45147.50,941.38,33196.16,164.14,10845.82,10103.35,742.47,0.0,conventional,2015,Albany,0.99
4,2015-02-01,0.99,70873.60,1353.90,60017.20,179.32,9323.18,9170.82,152.36,0.0,conventional,2015,Albany,0.99

In [22]:
# code date as numbers - code from lecture 19

In [23]:
first_day = df_train["Date"].min()

df_train_num = df_train.assign(
    Days_since=df_train["Date"].apply(lambda x: (x - first_day).days)
)
df_test_num = df_test.assign(
    Days_since=df_test["Date"].apply(lambda x: (x - first_day).days)
)

In [24]:
# df_train_num.head()

In [25]:
numeric_features = [
    "Total Volume",
    "4046",
    "4225",
    "4770",
    "Total Bags",
    "Small Bags",
    "Large Bags",
    "XLarge Bags",
    "AveragePriceNextWeek",
    "year"
]
categorical_features = [
    "type",
    "region"
]
drop_features = ["Total Bags", "Date"]
target = ["AveragePrice"]

In [26]:
# code from lecture 19
def preprocess_features(
    train_df,
    test_df,
    numeric_features,
    categorical_features,
    drop_features,
    target
):

    all_features = set(numeric_features + categorical_features + drop_features + target)
    if set(train_df.columns) != all_features:
        print("Missing columns", set(train_df.columns) - all_features)
        print("Extra columns", all_features - set(train_df.columns))
        raise Exception("Columns do not match")

    numeric_transformer = make_pipeline(
        SimpleImputer(strategy="median"), StandardScaler()
    )
    categorical_transformer = make_pipeline(
        SimpleImputer(strategy="constant", fill_value="missing"),
        OneHotEncoder(handle_unknown="ignore", sparse_output=False),
    )

    preprocessor = make_column_transformer(
        (numeric_transformer, numeric_features),
        (categorical_transformer, categorical_features),
        ("drop", drop_features),
    )
    preprocessor.fit(train_df)
    ohe_feature_names = (
        preprocessor.named_transformers_["pipeline-2"]
        .named_steps["onehotencoder"]
        .get_feature_names_out(categorical_features)
        .tolist()
    )
    new_columns = numeric_features + ohe_feature_names

    X_train_enc = pd.DataFrame(
        preprocessor.transform(train_df), index=train_df.index, columns=new_columns
    )
    X_test_enc = pd.DataFrame(
        preprocessor.transform(test_df), index=test_df.index, columns=new_columns
    )

    y_train = train_df[target]
    y_test = test_df[target]

    return X_train_enc, y_train, X_test_enc, y_test, preprocessor

In [27]:
X_train_enc, y_train, X_test_enc, y_test, preprocessor = preprocess_features(
    df_train_num,
    df_test_num,
    numeric_features + ["Days_since"],
    categorical_features,
    drop_features, target
)

In [28]:
lr = Ridge()
lr.fit(X_train_enc, y_train)
print(lr.score(X_train_enc, y_train))
print(lr.score(X_test_enc, y_test))

0.8495065049185478
0.786962688049372

In [29]:
# code from lecture 19
def score_lr_print_coeff(preprocessor, train_df, y_train, test_df, y_test, X_train_enc):
    lr_pipe = make_pipeline(preprocessor, Ridge())
    lr_pipe.fit(train_df, y_train)
    print("Train score: {:.2f}".format(lr_pipe.score(train_df, y_train)))
    print("Test score: {:.2f}".format(lr_pipe.score(test_df, y_test)))
    lr_coef = pd.DataFrame(
        data=lr_pipe.named_steps["ridge"].coef_.flatten(),
        index=X_train_enc.columns,
        columns=["Coef"],
    )
    return lr_coef.sort_values(by="Coef", ascending=False)

In [30]:
score_lr_print_coeff(preprocessor, df_train_num, y_train, df_test_num, y_test, X_train_enc)

Train score: 0.85
Test score: 0.79

                                Coef
AveragePriceNextWeek        0.314929
region_HartfordSpringfield  0.105664
region_SanFrancisco         0.100464
region_NewYork              0.083908
region_Philadelphia         0.061715
...                              ...
type_conventional          -0.059267
region_LosAngeles          -0.065342
region_SouthCentral        -0.077431
region_DallasFtWorth       -0.080662
region_Houston             -0.087174

[67 rows x 1 columns]

In [31]:
# OHE of the month - code from lecture 19

In [32]:
df_train_ohe = df_train.assign(
    Month=df_train["Date"].apply(lambda x: x.month_name())
)  # x.month_name() to get the actual string
df_test_ohe = df_test.assign(Month=df_test["Date"].apply(lambda x: x.month_name()))

In [33]:
df_train_ohe[["Date", "Month"]].sort_values(by="Month")

            Date      Month
1304  2017-04-30      April
9869  2016-04-17      April
9025  2016-04-24      April
3332  2017-04-30      April
3331  2017-04-23      April
...          ...        ...
11241 2016-09-04  September
11242 2016-09-11  September
11243 2016-09-18  September
11293 2017-09-03  September
18222 2017-09-24  September

[15441 rows x 2 columns]

In [34]:
X_train_enc, y_train, X_test_enc, y_test, preprocessor = preprocess_features(
    df_train_ohe, df_test_ohe, 
    numeric_features, 
    categorical_features + ["Month"], 
    drop_features,
    target
)

In [35]:
lr = Ridge()
lr.fit(X_train_enc, y_train)
print(lr.score(X_train_enc, y_train))
print(lr.score(X_test_enc, y_test))

0.8506938241489406
0.7951700645752183

In [36]:
score_lr_print_coeff(preprocessor, df_train_ohe, y_train, df_test_ohe, y_test, X_train_enc)

Train score: 0.85
Test score: 0.80

                                Coef
AveragePriceNextWeek        0.311934
region_HartfordSpringfield  0.109034
region_SanFrancisco         0.103828
region_NewYork              0.086924
region_Philadelphia         0.063748
...                              ...
type_conventional          -0.061145
region_LosAngeles          -0.067301
region_SouthCentral        -0.080391
region_DallasFtWorth       -0.083146
region_Houston             -0.090036

[78 rows x 1 columns]

We got .80 as test score!

In [37]:
# OHE as seasons - code from lecture 19

In [38]:
def get_season(month):
    SUMMER_MONTHS = ["June", "July", "August"] 
    SPRING_MONTHS = ["March", "April", "May"]
    WINTER_MONTHS = ["December", "January", "February"]
    AUTUMN_MONTHS = ["September", "October", "November"]
    if month in WINTER_MONTHS:
        return "Winter"
    elif month in AUTUMN_MONTHS:
        return "Autumn"
    elif month in SUMMER_MONTHS:
        return "Summer"
    else:
        return "Fall"

In [39]:
df_train_szn = df_train_ohe.assign(Season=df_train_ohe["Month"].apply(get_season))
df_test_szn = df_test_ohe.assign(Season=df_test_ohe["Month"].apply(get_season))

In [40]:
df_train_szn.head()

,Date,AveragePrice,Total Volume,4046,4225,4770,Total Bags,Small Bags,Large Bags,XLarge Bags,type,year,region,AveragePriceNextWeek,Month,Season
0,2015-01-04,1.22,40873.28,2819.50,28287.42,49.90,9716.46,9186.93,529.53,0.0,conventional,2015,Albany,1.24,January,Winter
1,2015-01-11,1.24,41195.08,1002.85,31640.34,127.12,8424.77,8036.04,388.73,0.0,conventional,2015,Albany,1.17,January,Winter
2,2015-01-18,1.17,44511.28,914.14,31540.32,135.77,11921.05,11651.09,269.96,0.0,conventional,2015,Albany,1.06,January,Winter
3,2015-01-25,1.06,45147.50,941.38,33196.16,164.14,10845.82,10103.35,742.47,0.0,conventional,2015,Albany,0.99,January,Winter
4,2015-02-01,0.99,70873.60,1353.90,60017.20,179.32,9323.18,9170.82,152.36,0.0,conventional,2015,Albany,0.99,February,Winter

In [41]:
X_train_enc, y_train, X_test_enc, y_test, preprocessor = preprocess_features(
    df_train_szn,
    df_test_szn,
    numeric_features,
    categorical_features + ["Season"],
    drop_features + ["Month"],
    target
)

In [42]:
coeff_df = score_lr_print_coeff(
    preprocessor, df_train_szn, y_train, df_test_szn, y_test, X_train_enc
)

Train score: 0.85
Test score: 0.79

In [43]:
coeff_df.loc[["Season_Fall", "Season_Summer", "Season_Winter", "Season_Autumn"]]

                   Coef
Season_Fall   -0.016496
Season_Summer  0.006262
Season_Winter -0.022583
Season_Autumn  0.032817

<!-- END QUESTION -->

<br><br><br><br>

## Exercise 2: very short answer questions

Each question is worth 2 points.

<!-- BEGIN QUESTION -->

### 2.1 Time series

_Points:_ 4

The following questions pertain to Lecture 19 on time series data:

1. Sometimes a time series has missing time points or, worse, time points that are unequally spaced in general. Give an example of a real world situation where the time series data would have unequally spaced time points.
2. In class we discussed two approaches to using temporal information: encoding the date as one or more features, and creating lagged versions of features. Which of these (one/other/both/neither) two approaches would struggle with unequally spaced time points? Briefly justify your answer.

<div class="alert alert-warning">

Solution_2.1
    
</div>

1. The added date of songs in a playlist on Spotify. Users can add new songs into their self-created playlist whenever they want, so the time points will be unequally spaced.
2. I think encoding the date as one or more features would be fine, but creating lagged versions of features would be problematic. Because it involves several (n: any natural number) previous measurements and if measurements are unequally spaced, the lagged feature would be have different spaced and therefore difficult to be created.

<!-- END QUESTION -->

<br><br>

<!-- BEGIN QUESTION -->

### 2.2 Survival analysis

_Points:_ 6

The following questions pertain to Lecture 20 on survival analysis. We'll consider the use case of customer churn analysis.

1. What is the problem with simply labeling customers are "churned" or "not churned" and using standard supervised learning techniques?
2. Consider customer A who just joined last week vs. customer B who has been with the service for a year. Who do you expect will leave the service first: probably customer A, probably customer B, or we don't have enough information to answer?
3. If a customer's survival function is almost flat during a certain period, how do we interpret that?

<div class="alert alert-warning">

Solution_2.2
    
</div>

1. The standard supervised learning considers the question as binary. However, customer attitudes might change over time. Some of them are "churned" before but are likely to change to "not churned" in the future. We are not sure when and who will change in the future since we only have up-to-date date and cannot predict future. Therefore, it might not be suitable to label them into one category as the binary problem.
2. We don't have enough information to answer. Customer A might leave early because they don't have much sunk cost and hence less loyalty, or Customer B might leave early as they receive a better perk from similar service of another company.
3. It means their stay will be very stable and not likely to be churned and leave the service during that period.

<!-- END QUESTION -->

<br><br>

## Submission instructions 

**PLEASE READ:** When you are ready to submit your assignment do the following:

1. Run all cells in your notebook to make sure there are no errors by doing `Kernel -> Restart Kernel and Clear All Outputs` and then `Run -> Run All Cells`. 
2. Notebooks with cell execution numbers out of order or not starting from “1” will have marks deducted. Notebooks without the output displayed may not be graded at all (because we need to see the output in order to grade your work).
3. Upload the assignment using PrairieLearn.
4. Make sure that the plots and output are rendered properly in your submitted file.